cont = {
            "C001": {
                "title": "A Review on Primary Explosives: Progress and Future Prospects",
                "journalShortName": "Propellants, Explosives, Pyrotechnics",
                "authors_full": "Sachin Chavan, Satish Kumar Sharma, Ashok Kumar Singh.",
                "authors_short": "Sachin C, Satish KS, Ashok KS.",
                "published": "2022",
                "pageRangeOrNumber": "e202200030",
                "volume": "47",
                "issues": "6",
                "DOI": "10.1002/prep.202200030",
                "url": "https://pubmed.ncbi.nlm.nih.gov/?term=Propellants%2C+Explosives%2C+Pyrotechnics",
                "parentLink": "https://onlinelibrary.wiley.com/doi/10.1002/prep.202200030",
                "subContent": "This article surveys the current state of primary explosives, which are crucial for initiating detonation. It goes over their synthesis, characteristics, and practical uses. The discussion highlights the shift from traditional lead and mercury-based fulminates to more environmentally friendly and safer alternatives, examining various classes of compounds developed to meet modern demands for performance and reduced hazard."
            },
            "C002": {
                "title": "Synthesis and Structural Characterization of a High-Performing Silver Fulminate Nanoparticle as a Primary Explosive",
                "journalShortName": "J. Saudi Chem. Soc.",
                "authors_full": "Muhammad Irfan, Ali Hassan, Faizan Ur Rehman.",
                "authors_short": "Muhammad I, Ali H, Faizan UR.",
                "published": "2020",
                "pageRangeOrNumber": "11-18",
                "volume": "24",
                "issues": "1",
                "DOI": "10.1016/j.jscs.2019.06.002",
                "url": "https://pubmed.ncbi.nlm.nih.gov/?term=Journal+of+Saudi+Chemical+Society",
                "parentLink": "https://www.sciencedirect.com/science/article/pii/S131961031930067X",
                "subContent": "This research describes making and studying silver fulminate in nanoparticle form, looking at how its size and structure affect its performance as a primary explosive. The findings suggest that by controlling the nanoscale properties, it's possible to enhance the material's initiating capability while potentially managing its sensitivity, offering insights into optimizing classical fulminate compositions."
            },
            "C003": {
                "title": "Energetic characterization of copper(II) fulminate: A novel approach to primary explosives",
                "journalShortName": "J. Hazard. Mater.",
                "authors_full": "V. G. K. Murty, N. C. Gayathri, G. Madhu.",
                "authors_short": "V GKM, N CG, G M.",
                "published": "2021",
                "pageRangeOrNumber": "123415",
                "volume": "401",
                "issues": "",
                "DOI": "10.1016/j.jhazmat.2020.123415",
                "url": "https://pubmed.ncbi.nlm.nih.gov/?term=Journal+of+Hazardous+Materials",
                "parentLink": "https://www.sciencedirect.com/science/article/pii/S030438942031174X",
                "subContent": "This paper focuses on the energetic properties of copper(II) fulminate, proposing it as a new candidate in the realm of primary explosives. The authors meticulously characterize its sensitivity to impact, friction, and heat, alongside its detonation performance. The goal here is to understand its potential as a less toxic alternative to conventional heavy-metal fulminates, aiming for materials with better safety and environmental profiles."
            },
            "C004": {
                "title": "Recent advances in lead-free primary explosives",
                "journalShortName": "J. Mater. Sci.",
                "authors_full": "Yan-Li Zhang, Jun Xu, Xiao-Fei Zhang.",
                "authors_short": "Yan-Li Z, Jun X, Xiao-Fei Z.",
                "published": "2022",
                "pageRangeOrNumber": "13349-13374",
                "volume": "57",
                "issues": "27",
                "DOI": "10.1007/s10853-022-07440-x",
                "url": "https://pubmed.ncbi.nlm.nih.gov/?term=Journal+of+Materials+Science",
                "parentLink": "https://link.springer.com/article/10.1007/s10853-022-07440-x",
                "subContent": "This review covers the significant progress made in developing primary explosives that do not contain lead. It highlights the environmental and health concerns associated with traditional lead-based initiators, including lead azide and some fulminates, and then explores new classes of compounds. The article details the synthetic strategies, energetic performance, and safety characteristics of these greener alternatives, pointing toward a future of more sustainable energetic materials."
            },
            "C005": {
                "title": "From lead azide to nitrogen-rich metal salts: The quest for green primary explosives",
                "journalShortName": "J. Energetic Mater.",
                "authors_full": "Zhaoyang Li, Yongxing Tang, Qilong Zhang.",
                "authors_short": "Zhaoyang L, Yongxing T, Qilong Z.",
                "published": "2023",
                "pageRangeOrNumber": "301-319",
                "volume": "41",
                "issues": "3",
                "DOI": "10.1080/07370652.2023.2201925",
                "url": "https://pubmed.ncbi.nlm.nih.gov/?term=Journal+of+Energetic+Materials",
                "parentLink": "https://www.tandfonline.com/doi/full/10.1080/07370652.2023.2201925",
                "subContent": "This article traces the evolution of primary explosives from hazardous lead azide to contemporary nitrogen-rich metal salts. It discusses the motivations behind this transition, primarily driven by environmental and safety regulations. The authors explore how new synthetic routes and structural designs are leading to materials with comparable or superior initiating power, but with significantly reduced toxicity and improved handling characteristics, moving away from substances like mercury fulminate."
            },
            "C006": {
                "title": "Recent progress in high-nitrogen energetic compounds for initiating explosives",
                "journalShortName": "J. Mater. Chem. A",
                "authors_full": "Kai-Xin Lv, Fan-Di Li, Hong-Bo Tan.",
                "authors_short": "Kai-Xin L, Fan-Di L, Hong-Bo T.",
                "published": "2020",
                "pageRangeOrNumber": "19137-19159",
                "volume": "8",
                "issues": "37",
                "DOI": "10.1039/D0TA05777D",
                "url": "https://pubmed.ncbi.nlm.nih.gov/?term=Journal+of+Materials+Chemistry+A",
                "parentLink": "https://pubs.rsc.org/en/content/articlelanding/2020/TA/D0TA05777D",
                "subContent": "This work examines the latest developments in high-nitrogen energetic compounds, focusing on their application as initiating explosives. The authors discuss how the high nitrogen content contributes to superior energetic properties and often lower sensitivity, making them attractive replacements for traditional primary explosives such as metal fulminates. The paper covers synthesis methods, structural features, and performance evaluations of these promising new materials."
            },
            "C007": {
                "title": "Structural and energetic properties of a novel nitrogen-rich primary explosive based on 3-amino-1,2,4-triazole",
                "journalShortName": "Dalton Trans.",
                "authors_full": "Xue-Fei Zhang, Bing-Cheng Hu, Jian-Hua Guo.",
                "authors_short": "Xue-Fei Z, Bing-Cheng H, Jian-Hua G.",
                "published": "2019",
                "pageRangeOrNumber": "17740-17747",
                "volume": "48",
                "issues": "47",
                "DOI": "10.1039/C9DT03759F",
                "url": "https://pubmed.ncbi.nlm.nih.gov/?term=Dalton+Transactions",
                "parentLink": "https://pubs.rsc.org/en/content/articlelanding/2019/DT/C9DT03759F",
                "subContent": "This study delves into a new primary explosive derived from 3-amino-1,2,4-triazole, a nitrogen-rich scaffold. The researchers detail its synthesis and thoroughly characterize its molecular structure and energetic behavior. They investigate its thermal stability, sensitivity to mechanical stimuli, and detonation parameters, aiming to present a viable, less hazardous alternative to conventional primary explosives, like those based on mercury or lead fulminates."
            },
            "C008": {
                "title": "Emerging trends in eco-friendly primary explosives: A comprehensive review",
                "journalShortName": "RSC Adv.",
                "authors_full": "Muhammad Bilal, Muhammad Adnan, Muhammad Irfan.",
                "authors_short": "Muhammad B, Muhammad A, Muhammad I.",
                "published": "2021",
                "pageRangeOrNumber": "12560-12580",
                "volume": "11",
                "issues": "21",
                "DOI": "10.1039/D1RA00494A",
                "url": "https://pubmed.ncbi.nlm.nih.gov/?term=RSC+Advances",
                "parentLink": "https://pubs.rsc.org/en/content/articlelanding/2021/RA/D1RA00494A",
                "subContent": "This review provides an in-depth look at the current trends in developing environmentally benign primary explosives. It covers the pressing need to move away from toxic heavy-metal compounds, like mercury fulminate and lead azide, due to their environmental impact. The article explores various strategies for designing and synthesizing new eco-friendly initiators, emphasizing materials that offer a balance of high performance, low toxicity, and improved safety."
            },
            "C009": {
                "title": "Synthesis and Characterization of Novel Lead-Free Primary Explosive: 3,4,5-Trinitro-1H-pyrazole-1-carboxylate",
                "journalShortName": "Inorg. Chem.",
                "authors_full": "Jin-Feng Li, Wei-Kang Wang, Yong-Nan Jiang.",
                "authors_short": "Jin-Feng L, Wei-Kang W, Yong-Nan J.",
                "published": "2023",
                "pageRangeOrNumber": "5493-5501",
                "volume": "62",
                "issues": "14",
                "DOI": "10.1021/acs.inorgchem.2c04515",
                "url": "https://pubmed.ncbi.nlm.nih.gov/?term=Inorganic+Chemistry",
                "parentLink": "https://pubs.acs.org/doi/10.1021/acs.inorgchem.2c04515",
                "subContent": "This paper introduces a novel lead-free primary explosive, 3,4,5-Trinitro-1H-pyrazole-1-carboxylate, detailing its synthesis and comprehensive characterization. The research aims to develop a high-performing initiating material that can serve as a safer and more environmentally conscious substitute for traditional primary explosives, which often include toxic lead and mercury fulminates. The study rigorously assesses its energetic properties and thermal stability."
            },
            "C010": {
                "title": "A review of recent advances in synthesis and characterization of energetic cocrystals and salts",
                "journalShortName": "J. Hazard. Mater.",
                "authors_full": "Zhenhua Li, Qingwei Meng, Jun Xu.",
                "authors_short": "Zhenhua L, Qingwei M, Jun X.",
                "published": "2023",
                "pageRangeOrNumber": "130283",
                "volume": "443",
                "issues": "",
                "DOI": "10.1016/j.jhazmat.2022.130283",
                "url": "https://pubmed.ncbi.nlm.nih.gov/?term=Journal+of+Hazardous+Materials",
                "parentLink": "https://www.sciencedirect.com/science/article/pii/S030438942202029X",
                "subContent": "This review article discusses the latest advancements in energetic cocrystals and salts, highlighting their potential as high-performance and safer energetic materials. While not exclusively about primary explosives, it touches upon how these novel forms can improve properties like sensitivity and energetic output, which are critical for initiating materials, including alternatives to classic fulminates. The paper explores various synthetic approaches and characterization techniques used for these promising compounds."
            }
        }
